name: Build and Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: ${{ secrets.AWS_REGION }}

    - name: Build and push Docker image
      id: build-image
      run: |
        docker buildx build --platform linux/amd64 -t ${{ secrets.ECR_REPOSITORY }}:latest .
        docker push ${{ secrets.ECR_REPOSITORY }}:latest

    - name: Deploy to ECS
      env:
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws ecs update-service --cluster your-cluster-name --service your-service-name --force-new-deployment